### ISSUE TITLE
stuck with user certificate in system

### ISSUE THREAD

**Issue by hyber-code** [NVISOsecurity/MagiskTrustUserCerts#20]
module did not automatically removed the user certificates from system , now i am stuck with old certificate activating again and again and chrome throwing diff ssl errors,

i have termux installed , can you please point me how to manually remove the certificates, thank you

**Comment by TheDauntless** [comment]
For anyone else coming into this issue: It's very weird (/impossible?) to remove the module without removing the certificates, since the certificates are located in the module directory and then automatically merged with /system. Since /system is never modified (this is how Magisk works), it's not possible that the certificate remained on /system after the module was removed.

So maybe the module itself was not removed, which would be a Magisk troubleshooting issue rather than a module issue.
