### ISSUE TITLE
MIUI 12 Android 10 is not supported

### ISSUE THREAD

**Issue by chiefTop** [NVISOsecurity/MagiskTrustUserCerts#22]
In miui12, after importing the burpsuite user certificate, the packet cannot be caught.

**Comment by TheDauntless** [comment]
Hi @chiefTop can you give a little bit more info? There are many different reasons why a MitM could still fail, and that's not something this script is meant to solve.

Please take a look at https://blog.nviso.eu/2020/11/19/proxying-android-app-traffic-common-issues-checklist/ and identify what the issue is. This Magisk Module will fix the "Is your Burp certificate installed as a root certificate?" issue.
