### ISSUE TITLE
Does not seem to work on A12

### ISSUE THREAD

**Issue by swablueme** [NVISOsecurity/MagiskTrustUserCerts#24]
Just tried to run this on  Android 12 and the notification doesn't show up and my traffic is not being decrypted.
Ripperoni...

**Comment by mikrodotnet** [comment]
I'm having the same issue. I'm on a Google Pixel 3a, rooted with Magisk. Can anyone make this work on Android 12?

**Comment by TheDauntless** [comment]
I've tested this on a Galaxy S8 with LinageOS 19 (Android 12) and it works.

Are you sure the Android version is the issue, and not the application? Do you have a publicly available demo application?

**Comment by TheDauntless** [comment]
Was able to test this on an A12 Pixel 6, and I couldn't reproduce your bug. 

I'm closing this, but if anybody else has a device that doesn't work, feel free to comment.

**Comment by ekko-zhao** [comment]
I'm having the same issue. I'm on a Google Pixel XL, rooted with Magisk,Android 10。

**Comment by xzrvr** [comment]
same issue on s10e (SM-G970F), ill just stick with another module for now

**Comment by TheDauntless** [comment]
I've just run another test:
- Stock Galaxy S20 FE 5G
- Rooted with Magisk
- Install burp cert as user cert
- Restart device to trigger module
=> All non-pinned HTTPS requests show up.

There is an issue with Chrome and required certificate transparency (CT), but that's a chrome specific issue which actually indicates that the module is working, because Chrome only forces CT on system certificates, not user certificates.

**Comment by swablueme** [comment]
@TheDauntless I've learnt more about cert pinning and have managed to sniff cert pinned and un cert pinned requests with this module after 2 years.
